loaded = true
[[account_configs]]
enable = true
enable_in_github_action = true
in_safe_mode = false
name = "默认账号名-1"
login_mode = "auto_login"
cannot_bind_dnf = false
drift_send_qq_list = []
dnf_13_send_qq_list = []
spring_fudai_receiver_qq_list = []
enable_firecrackers_invite_friend = false
enable_majieluo_invite_friend = false
enable_majieluo_lucky = false
ozma_ignored_rolename_list = []
gonghui_rolename_huizhang = ""
gonghui_rolename_huiyuan = ""
dnf_bbs_cookie = ""
colg_cookie = ""
huya_cookie = ""
comic_lottery = false
take_award_34c_server_id = ""
take_award_34c_role_id = ""
enable_auto_match_xinyue_team = false
wegame_guoqing_exchange_items = []
sDeviceID = "391319fb-f0a9-11ec-89d9-3413e82f7c2b"
aes_key = "84e6c6dc0f9p4a56"
rsa_public_key_file = "utils/reference_data/public_key.der"
g_tk = "127732478"
[[account_configs.exchange_items]]
iGoodsId = "753"
sGoodsName = "装备品级调整箱（5个）"
count = 0

[[account_configs.exchange_items]]
iGoodsId = "3089"
sGoodsName = "高级装扮兑换券（7天）（每周限量1次）"
count = 0

[[account_configs.exchange_items]]
iGoodsId = "3120"
sGoodsName = "魔界抗疲劳秘药（10点）（每周限量1次）"
count = 0

[[account_configs.exchange_items]]
iGoodsId = "3088"
sGoodsName = "装备品级调整箱（2个）（每月限兑1次）"
count = 0

[[account_configs.exchange_items]]
iGoodsId = "110"
sGoodsName = "成长之契约（3天）（每年限兑5次）"
count = 0

[[account_configs.exchange_items]]
iGoodsId = "107"
sGoodsName = "达人之契约（3天）（每天限兑2次）"
count = 0

[[account_configs.exchange_items]]
iGoodsId = "382"
sGoodsName = "晶之契约（3天）（每天限兑2次）"
count = 0

[[account_configs.exchange_items]]
iGoodsId = "381"
sGoodsName = "复活币（每天限兑2次）"
count = 0

[[account_configs.exchange_items]]
iGoodsId = "754"
sGoodsName = "装扮属性调整箱（高级）（1个）（每天限兑1次）"
count = 0

[[account_configs.exchange_items]]
iGoodsId = "383"
sGoodsName = "闪亮的雷米援助(15个)"
count = 0

[[account_configs.xinyue_operations]]
iFlowId = "747759"
package_id = "1537696"
sFlowName = "超级远古精灵秘药（持续30分钟）(需25点勇士币)"
count = 0

[[account_configs.xinyue_operations]]
iFlowId = "747693"
package_id = "1537766"
sFlowName = "装备提升礼盒(需10点成就点)"
count = 0

[[account_configs.xinyue_operations]]
iFlowId = "747759"
package_id = "1537690"
sFlowName = "装备提升礼盒(需30点勇士币)(每日20次)"
count = 0

[[account_configs.xinyue_operations]]
iFlowId = "747672"
package_id = ""
sFlowName = "复活币*3礼袋(日限10)(需8成就点)"
count = 0

[[account_configs.xinyue_operations]]
iFlowId = "821281"
package_id = ""
sFlowName = "新版复活币*1(日限100)(需1点勇士币)"
count = 0

[[account_configs.xinyue_operations]]
iFlowId = "749075"
package_id = ""
sFlowName = "高级装扮兑换券(需400点勇士币)（每月1次）"
count = 0

[[account_configs.xinyue_app_operations]]
name = "兑换复活币"
encrypted_raw_http_body = []

[[account_configs.xinyue_app_operations]]
name = "兑换雷米"
encrypted_raw_http_body = []

[[account_configs.xinyue_app_operations]]
name = "兑换霸王契约"
encrypted_raw_http_body = []


[account_configs.account_info]
uin = "o123456789"
skey = "@a1b2c3d4e"
account = "123456789"
password = "使用账号密码自动登录有风险_请理解这个功能到底如何使用你的账号密码后再决定是否使用"
[account_configs.function_switches]
disable_most_activities = false
disable_share = false
disable_login_mode_normal = false
disable_login_mode_qzone = false
disable_login_mode_iwan = false
disable_login_mode_guanjia = false
disable_login_mode_xinyue = false
get_djc = true
make_wish = true
get_xinyue = true
get_credit_xinyue_gift = true
get_heizuan_gift = true
get_xinyue_sailiyam = true
get_wegame_guoqing = true
get_dnf_1224 = true
get_dnf_shanguang = true
get_qq_video = true
get_dnf_female_mage_awaken = true
get_dnf_rank = true
get_dnf_helper_chronicle = true
get_hello_voice = true
get_dnf_carnival = true
get_dnf_carnival_live = true
get_dnf_dianzan = true
get_dnf_welfare = true
get_xinyue_financing = true
get_xinyue_cat = true
get_xinyue_weekly_gift = true
get_dnf_drift = true
get_majieluo = true
get_dnf_helper = true
get_warm_winter = true
get_qq_video_amesvr = true
get_dnf_bbs_signin = true
get_dnf_luodiye = true
get_dnf_wegame = true
get_wegame_new = true
get_spring_fudai = true
get_dnf_fuqian = true
get_dnf_collection = true
get_firecrackers = true
get_dnf_ozma = true
get_colg_signin = true
get_xinyue_app = true
get_dnf_pk = true
get_dnf_xinyue = true
get_dnf_strong = true
get_dnf_comic = true
get_dnf_13 = true
get_dnf_my_story = true
get_dnf_reserve = true
get_dnf_anniversary = true
get_dnf_kol = true
get_maoxian_start = true
get_maoxian = true
get_xiaojiangyou = true
get_dnf_gonghui = true
dnf_gonghui_enable_lottery = false
get_dnf_mingyun_jueze = true
get_dnf_guanhuai = true
get_dnf_relax_road = true
get_huya = true
get_dnf_vote = true
get_dnf_reservation = true
get_dnf_memory = true
get_dnf_game = true
get_dnf_interactive = true
get_mojieren = true
get_dnf_my_home = true
get_team_happy_new_year = true
get_dnf_card_flip = true
get_ark_lottery = true
get_dnf_warriors_call = true
get_vip_mentor = true
get_dnf_super_vip = true
get_dnf_yellow_diamond = true
get_dnf_club_vip = true
get_guanjia = true
[account_configs.mobile_game_role_info]
game_name = "任意手游"
[account_configs.ark_lottery]
lucky_dnf_server_id = ""
lucky_dnf_role_id = ""
need_take_awards = false
show_status = true
show_color = ""
[account_configs.vip_mentor]
take_index = 2
guanhuai_dnf_server_id = ""
guanhuai_dnf_role_id = ""
[account_configs.dnf_helper_info]
userId = ""
nickName = ""
token = ""
uniqueRoleId = ""
pNickName = ""
pUserId = ""
enable_auto_match_dnf_chronicle = false
chronicle_lottery = false
chronicle_exchange_items = []
[account_configs.hello_voice]
hello_id = ""
[account_configs.firecrackers]
enable_lottery = false
exchange_items = []
[account_configs.ark_lottery.act_id_to_cost_all_cards_and_do_lottery]
3886 = false
4166 = false
4261 = false
4437 = false
4473 = false
4495 = false
10001 = false
10002 = false
10003 = false
10004 = false
10005 = false
10006 = false

[common]
run_first_account_only = false
account_count = 1
test_mode = false
enable_in_safe_mode_accounts = false
_show_usage = false
config_ui_enable_high_dpi = false
bypass_proxy = true
disable_cmd_quick_edit = true
enable_change_cmd_buffer = true
enable_max_console = true
enable_min_console = false
enable_multiprocessing = true
enable_super_fast_mode = true
multiprocessing_pool_size = -1
enable_multiprocessing_login = true
force_use_portable_chrome = false
force_use_chrome_major_version = 0
http_timeout = 10
_debug_show_chrome_logs = false
run_in_headless_mode = false
log_level = "info"
max_logs_size = 1024
keep_logs_size = 512
check_update_on_start = false
check_update_on_end = false
readme_page = "https://github.com/fzls/djc_helper/blob/master/README.MD"
changelog_page = "https://github.com/fzls/djc_helper/blob/master/CHANGELOG.MD"
github_mirror_sites = [ "api.mtr.pub", "gh.gcdn.mirr.one", "hub.0z.gs", "hub.fastgit.xyz",]
auto_updater_dlc_purchase_url = "https://www.kami.vip/purchasing?link=auto-updater"
pay_by_month_purchase_url = "https://www.kami.vip/purchasing?link=pay-by-month"
netdisk_link = "https://fzls.lanzoup.com/s/djc-helper"
netdisk_link_for_report = "https://fzls.lanzouw.com/s/djc-helper"
qq_group = 791343073
auto_update_on_start = false
allow_only_one_instance = true
try_auto_bind_new_activity = true
force_sync_bind_with_djc = true
notify_pay_expired_in_days = 7
majieluo_send_card_target_qq = ""
xinyue_send_card_target_qq = ""
ark_lottery_summary_show_color = ""
cost_all_cards_and_do_lottery_on_last_day = true
auto_send_card_target_qqs = []
enable_send_card_by_request = true
scode_list_accept_give = []
scode_list_accept_ask = []
majieluo_invite_uin_list = []
enable_alipay_redpacket_v2 = true
sailiyam_visit_target_qqs = []
[[common.fixed_teams]]
enable = false
id = "1"
members = [ "小队第一个账号的QQ号", "小队第二个账号的QQ号",]

[[common.fixed_teams]]
enable = false
id = "2"
members = [ "小队第一个账号的QQ号", "小队第二个账号的QQ号",]

[common.log_colors]

[common.login]
max_retry_count = 6
retry_wait_time = 1200
open_url_wait_time = 3
load_page_timeout = 15
load_login_iframe_timeout = 8
login_timeout = 60
login_finished_timeout = 60
auto_resolve_captcha = true
move_captcha_delta_width_rate = 0.2
recommended_retry_wait_time_change_rate = 0.125
enable_auto_click_avatar_in_auto_login = true
enable_auto_click_avatar_in_qr_login = true

[common.retry]
request_wait_time = 2
max_retry_count = 3
retry_wait_time = 5

[common.xinyue]
submit_task_after = 0

[common.majieluo]
dahao_index = ""
xiaohao_indexes = []
xiaohao_qq_list = []
scode_1 = ""
scode_2 = ""
scode_3 = ""
