name: Run On Windows

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
  schedule:
    # 参考 https://jasonet.co/posts/scheduled-actions/
    # note: 这里是GMT时间，北京时间减去八小时即可。如北京时间 22:30 => GMT 14:30
    # re: 目前已知在github的action runner上，访问国内相关的接口会大概率超时，如pskey和skey的获取，以及访问道聚城相关接口，故而先测试性的每日十点半运行一次，其他时候就不运行了
    # minute hour day month dayOfWeek
    - cron: '00 14 * * *' # GMT 14:30 => 北京时间 22:30
    #- cron: '30 16 * * *' # GMT 16:30（前一天） => 北京时间 00:30

jobs:
  run:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Set time zone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Shanghai"
          timezoneMacos: "Asia/Shanghai"
          timezoneWindows: "China Standard Time"

      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"

      - name: pip cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Requirements Windows
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Run
        env:
          DJC_HELPER_CONFIG_TOML: ${{ secrets.DJC_HELPER_CONFIG_TOML }}
        run: |
          echo "$DJC_HELPER_CONFIG_TOML" > ./config.toml
          python main.py
